Add commands from the demo gif to the README.md as text
ofek/pyapp pull request #57
Opened 2023-12-13 23:21 UTC by anze3db

Can we add the commands from the gif in text form so that they are easy to copy/paste? This will make it easier to try out the project locally.

2023-12-15 22:35 UTC, danielhoherd commented
god yes. the first thing i noticed when i loaded up this project was how terrible the experience of looking at the example was. just show me the full terminal buffer.

2023-12-31 23:36 UTC, ofek commented on README.md
> +```
See the [how-to](https://ofek.dev/pyapp/latest/how-to/) for a detailed example walkthrough.

2023-12-31 23:37 UTC, ofek requested changes

2023-12-31 23:37 UTC, ofek commented on README.md
> +```
```suggestion
See the [how-to](https://ofek.dev/pyapp/latest/how-to/) for a detailed example walkthrough.
```

2023-12-31 23:37 UTC, ofek commented on README.md
> +```
Documentation coming later tonight!

2024-01-01 02:46 UTC, ofek approved these changes
Thank you!

2024-01-01 03:13 UTC, merged

2024-01-01 03:50 UTC, ofek commented
https://ofek.dev/pyapp/latest/how-to/